### ISSUE TITLE
Establish Origami’s process

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-website#129]
We had a meeting about process today, this was the agenda written by Rowan Manning:

## introduction 

Later last year we all discussed at various points the need to revise our process, and come up with something that works for the team. The existing processes were created a long time ago with a completely different group of people, let's decide what will work for us.
The things we need to cover/come up with a solution for:
* How we do day-to-day planning and prioritisation
* How we do longer term planning, e.g. what our priorities are for a year or quarter
* How we capture what we're doing well and what needs improvement, and make sure our process can be iterated on and doesn't stagnate

## agenda
13:05–13:10: post-it exercise, what’s good and bad about the way the team works
13:10–13:20: discuss the exercise, group post-its, prioritise what we’d like to discuss
13:20–13:30: short break and/or padding time
13:30–13:50: discuss what we need from day-to-day planning and prioritisation, including potential solutions
13:50–14:10: discuss what we need from longer-term planning and prioritisation, including potential solutions
14:10–14:20: short break and/or padding time
14:20–14:40: discuss what we need from an iteration and feedback process, including potential solutions
14:40–end: write out draft processes together, set up any required meetings

———

here are some notes from the session:

## day-to-day planning

The current process is a reminder from Slackbot every morning in our internal channel, we reply to it with our updates.
We like the current process, but it is lacking in searchability, and it gets lost in the Slack.
We’re going to move it to a single-purpose channel called `#origami-standup`, which will give us a better view of history.
Maybe we’ll learn that we want more from it, and build another solution, but this is the least-effort solution that gives us most of what we want :)

## longer-term planning

Current process is the Summit which is long, infrequent and irregular.
We like that it celebrates success, and we like that it is focused longer term planning.

We’re going to introduce 6-week cycles on top of which the members of the team can build their own structure. We’re a team that is used to having a lot of agency. A light structure of this kind works as waypoints, around which we can build whatever works for us.
These will be punctuated by a re-worked Open Meeting. Clarifying the purpose of the meeting, we’ll have Origami Office Hours in a public space. During this we’ll also update each other on what we’ve been up to, office hours for each other too.
We’re also going to have larger meetings on a longer schedule (perhaps 8 months) to think about the bigger plans for Origami’s future. Before these meetings we will send out a survey, and host a meeting with our customers to find out what they need from us and want from us.
We’ll also revive Origami’s Github Project and figure out how to get all origami-related issues into it so we have a single place to view everything.

**Comment by chee** [comment]
Any time any conversation about process wants to happen, we can open up an issue on here and atlk about it. We can also then bring those proposals/problems up at the next 6-week meeting.

I think maybe a forum different than Github issues might be better for this, because not every converstion suits having an open/closed state. But, similar to our plan to repurpose the existing Slackbot and our plan to revive Origami’s Github Project board, this is a least-friction way of getting something going that we can iterate on.

**Comment by chee** [comment]
Any time any conversation about process wants to happen, we can open up an issue on here and atlk about it. We can also then bring those proposals/problems up at the next 6-week meeting.

I think maybe a forum different than Github issues might be better for this, because not every converstion suits having an open/closed state. But, similar to our plan to repurpose the existing Slackbot and our plan to revive Origami’s Github Project board, this is a least-friction way of getting something going that we can iterate on.

**Comment by chee** [comment]
We talked too about how to iterate and make sure we don’t stagnate. My proposal is that anything anyone wants to talk about regarding process can be an issue here. We have lots of great tools for working on our products, and we should turn them inwards and use them to work on our team.

Open up an issue on here and we can take our time to think about it and reply from the comfort of our own homes while drinking a turmeric-based heated oat drink. We can also then bring those proposals/problems up at the next 6-week meeting.

I think maybe a forum different than Github issues might be better for this, because not every thing one might talk about suits having an open/closed state. But, similar to our plan to repurpose the existing Slackbot and our plan to revive Origami’s Github Project board, this is a least-friction way of getting something going that we can iterate on.

Once we’re using it, we’ll get an idea of the sort of thing we want from our system and we can iterate on it and change it to suit us.

**Comment by notlee** [comment]
This is great 🎉 

> We’re also going to have larger meetings on a longer schedule (perhaps 8 months) to think about the bigger plans for Origami’s future. Before these meetings we will send out a survey, and host a meeting with our customers to find out what they need from us and want from us.

Is that supposed to read "(perhaps 6 months)"?

**Comment by chee** [comment]
oh! perhaps it should, if 6 months is what we want. 

maybe we should do it in weeks, actually, as a multiple of 6. 
so that we can replace a cycle-start meeting with the Big Cycle meeting. 

so we’d say every 6 cycles, or every 4 or whatever

**Comment by rowanmanning** [comment]
@Financial-Times/origami-core we just finished our first planning meeting, if you have feedback on how it went then maybe here is a good place to mention it 🙂

**Comment by chee** [comment]
it was too hot in the room, no oxygen.

Now that we have done one, the next ones will be much smoother! I liked trying to write down everything we have, and figure out what we want to do now. It was great to look at it all and then actually get an idea of what is good stuff to do. The prioritisation session went really well.

I liked that it was casual but focused. Next time I'd like more of an understanding going into it of the shape of the meeting, but I think we'll continue refining that over the course of the Friday meetings. and it'll be like "OK! we've come up with all these new things since last time, let's decide which ones we're doing and when"

it was good! i feel good about knowing what i should be focusing on.

**Comment by JakeChampion** [comment]
> it was too hot in the room, no oxygen.

Very much agree, let's try to avoid the perimeter basement meeting rooms if we can.

> Now that we have done one, the next ones will be much smoother! I liked trying to write down everything we have, and figure out what we want to do now. It was great to look at it all and then actually get an idea of what is good stuff to do. The prioritisation session went really well.

Again, I agree, I found it interesting that I wrote down work I was currently doing and future work and came to the realisation that a specific piece of future work (build-service v2 conflicts) should be what I work on ASAP.

> I liked that it was casual but focused. Next time I'd like more of an understanding going into it of the shape of the meeting, but I think we'll continue refining that over the course of the Friday meetings. and it'll be like "OK! we've come up with all these new things since last time, let's decide which ones we're doing and when"

Yep, I think I had no idea what to expect going into the meeting (likely my own fault). Now I know to spend a moment before the meeting thinking about any new items which have come up sicne the previous meeting.

> it was good! i feel good about knowing what i should be focusing on.

:-D

**Comment by JakeChampion** [comment]
> I think maybe a forum different than Github issues might be better for this, because not every thing one might talk about suits having an open/closed state. But, similar to our plan to repurpose the existing Slackbot and our plan to revive Origami’s Github Project board, this is a least-friction way of getting something going that we can iterate on.

We should make a note to review how the GitHub issue usage for process discussions in the next meeting.

**Comment by chee** [comment]
we did it!
