### ISSUE TITLE
'Advanced' topics

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/origami-website#13]
The current docs have a lot of granular information which makes it bloated and unmanageable. This is an (ongoing) list of topics we can set aside and potentially consider for a more specialised/granular section, later:

- [Shrinkwrapping](https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/developer-guide/module-versioning.md#shrinkwrapping) — related to https://github.com/Financial-Times/ft-origami/issues/468
- [Beta releases](https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/developer-guide/module-versioning.md#beta-releases)
- [Customising CTMs](https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/developer-guide/cuts-the-mustard.md#customising-your-cuts-the-mustard-test)
- [Multiple CTMs](https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/developer-guide/cuts-the-mustard.md#multiple-cuts-the-mustards)
- [Details about browser support](https://docs.google.com/document/d/1mByh6sT8zI4XRyPKqWVsC2jUfXHZvhshS5SlHErWjXU)
- [Details about Polyfills that go beyond referencing Polyfill.io and its docs](https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/developer-guide/using-the-polyfill-service.md#using-polyfillio-with-other-polyfills)

**Comment by notlee** [comment]
Hi :D I'm going to close this issue as it's quite old and many of the example topics have been updated or are no longer relevant. For example the shrinkwrap parameter is no longer used in v3 of the build service; the spec has been relaxed to the point of deletion; and we have new tutorials on [customising components](https://origami.ft.com/docs/components/customisation/) and [creating components](https://origami.ft.com/docs/tutorials/create-a-new-component-part-1/).
