### ISSUE TITLE
Make tutorials a top-level navigation item

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-website#174]
If `tutorials` was added to the top navigation then "Origami on npm" could be a category of tutorial

_Originally posted by @chee in https://github.com/Financial-Times/origami-website/pull/172#issuecomment-595849330_

**Comment by notlee** [comment]
"Origami on npm" is the default now with the migration guide written as an announcement so I think we can close this issue? I think the few tutorials we still have make sense under the docs section. The create new component tutorial is kinda a category of a tutorial with many parts like the npm tutorial was but it uses an in-page nav: https://origami.ft.com/docs/tutorials/create-a-new-component-part-1/
