### ISSUE TITLE
Describe what each of the origamiCategorys mean

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-website#180]
Currently we have 4 `origamiCategory`s:

* components
* primitives
* utilities
* layouts

I don't know if we have descriptions of these anywhere?

We should update the manifest spec to have descriptions of them i think, but I don't know what those should be

#### layouts

As far as i can tell, nothing uses an `origamiCategory` of `layouts`. I don't know what it means.

#### utilities

Utilities appear to vaguely be javascript or sass tools that don't have an appearance?

<details>
<summary> <code>utilities</code> covers these</summary>
autoinit
comment-utilities
date
errors
expander
icons
layers
lazy-load
normalise
toggle
utils
viewport
comment-api
font-assets
</details>

#### primitives

primitives appear to be things that are required by lots of other origami components. not quite sure what precisely distinguishes them from utilities

<details>
<summary> <code>primitives</code> covers these</summary>
colors
fonts
grid
loading
typography
visual-effects
</details>

#### components

these are full components with mark-up

<details>
<summary> <code>components</code> covers these</summary>
banner
buttons
comments
comment-ui
cookie-message
footer
footer-services
forms
ft-affiliate-ribbon
header
header-services
labels
layout
message
overlay
quote
share
spacing
stepped-progress
subs-card
syntax-highlight
table
table
tabs
teaser
teaser-collection
tooltip
tracking
video
gallery
meter
</details>

**Comment by notlee** [comment]
>As far as i can tell, nothing uses an origamiCategory of layouts. I don't know what it means.

`o-techdocs` used to be under the layout category apparently. Components used to show in the registry under a category heading ([web archive](https://web.archive.org/web/20171012111547/http://registry.origami.ft.com/components)).
<img width="965" alt="Screenshot 2020-04-06 at 12 51 46" src="https://user-images.githubusercontent.com/10405691/78555678-74ebc700-7805-11ea-878a-84684d385033.png">

If components which layout a page go in that category, it's not super clear to me why o-grid isn't a layout. o-layout replaces o-techdocs, and both o-techdocs and o-layout also provide typography and other styles out of the box. I wonder if this was meant for complex "components" that basically style a whole page for you??

**Comment by notlee** [comment]
Agree utilities/primitives is unclear. 👍 I'd have thought utilities are no use on their own, don't have markup, and should be used to build other components. If that's the case these utils should be primitives:

- date expander icons normalise toggle

Leaving only these as utils:
- errors layers lazy-load utils viewport comment-api font-assets

**Comment by chee** [comment]
these are great, lee! thank you!

I think then we should come up with descriptions for each of the `origamiCategory`s and then put everything into the correct category!!

check these and see if i've missed any:)

## Layouts

Layouts are complex components that provide styles for the whole page

members:
layout (maybe grid?)

## Utilities

Utilities are Sass and JavaScript utilities that provide no markup, provide no classes and are used to encapsulate shared logic between components

members:
errors layers lazy-load utils viewport comment-api font-assets

## Primitives

Base components that provide minimal markup and are used by other components

members:
date expander icons normalise toggle (maybe grid?)

## Components

*_Having trouble writing this one..._*

Complete components that provide a...
use-case...
complex compone......

not sure

members:
banner buttons comments comment-ui cookie-message footer footer-services forms ft-affiliate-ribbon header header-services labels message overlay quote share spacing stepped-progress subs-card syntax-highlight table table tabs teaser teaser-collection tooltip tracking video gallery meter

**Comment by notlee** [comment]
Looks good! :D

Suggestion for a component description, smashing together what you outlined:
>Complete components built from primitives and utilities, which provide a user interface to cater for a usecase.

Definitely difficult to write... and it's kinda a confusing category now we're renaming the type to component. We should probably scrap most categories in v2, and only keep around categories for technical reasons if we want to fork the spec.

**Comment by chee** [comment]
hmm, now starting to think that things that provide utility classes like `o-toggle` should probably be utilities

**Comment by notlee** [comment]
>hmm, now starting to think that things that provide utility classes like o-toggle should probably be utilities

Hmmm yeah I see why. It has markup and styles but doesn't look like anything, it just hides and shows. But I like the clear-cut definition we have so far

I made a mistake though in a previous comment. o-lazy-load is not a utility as it has markup,  css, and js, it's a fully formed component.

**Comment by chee** [comment]
closed by https://github.com/Financial-Times/origami-website/pull/183 and a few more ^_^
