### ISSUE TITLE
Proposal: Update external tutorial links to open in a new tab

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-website#181]
We generally avoid links opening in a new tab in our docs so users can choose if they’d like a new tab or not. For example on a Mac by holding `cmd` when clicking.

Some users expect external links to open in a new tab though. Perhaps more
so on a tutorial page when referencing external resources whilst working 
through a page.

Proposal: update external links on tutorial pages to open in a new tab.

Suggested by Emma:
https://financialtimes.slack.com/archives/CVBRZ4K55/p1586857167002800

Discussion opened up to the broader design team here:
https://financialtimes.slack.com/archives/C8U9J5YJ2/p1586866165077900

**Comment by notlee** [comment]
Let's do this  (with a note on the link it opens in a new tab). If people are unfamiliar with opening new links in a new tab with the `cmd` key it could be quite disruptive to the multistep tutorial.

>Opening a page containing context-sensitive information, such as help instructions, or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab.
https://www.w3.org/TR/WCAG20-TECHS/G200.html

More guidelines have been added to o-typography too: https://github.com/Financial-Times/o-typography/pull/262

**Comment by JakeChampion** [comment]
Let's do this :-)
