### ISSUE TITLE
Remove o-brand spec requirement

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-website#282]
>Components which support brands must include the o-brand component as a dependency, which provides functions and mixins to customise a component per brand.

The above should be removed because it does not account for components which support all brands, without brand specific logic e.g. a JS utility. Or we could consider making it a should. If components implement brands in the same way they are easier to work with based on experience with another component

@chee pointed this spec issue out here :) https://github.com/Financial-Times/o-toggle/pull/69#pullrequestreview-528495735

**Comment by JakeChampion** [comment]
We could add an extra part to this section which states o-brand **must** be used if the component has brand specific features/designs, that way we ensure components have the same way to be configured for a brand and it allows generic components which work for all brands to not require o-brand as a dependency such as o-toggle. 

Something like this:
>Components which support brands and have brand specific features/designs must include the o-brand component as a dependency, which provides functions and mixins to customise a component per brand.

What do you both think @notlee and @chee?

**Comment by notlee** [comment]
Sounds good to me @JakeChampion

**Comment by chee** [comment]
yes, that sounds good to me
