### ISSUE TITLE
Are component data attributes required to have a prefix?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-website#284]
Most components prefix data attributes with the component name. Does the spec require it? And if not, should it? 
E.g. `data-o-message-close="false"` over `data-close="false"`?

I think we should prefix them and update the spec if required to avoid conflicts with user attributes if we add new options to a component.

**Comment by chee** [comment]
my vote is yes, we should prefix them!

**Comment by JakeChampion** [comment]
Yes, they are required to have a prefix of the component name already 👍 
>The component must be configurable using data attributes on the component’s root HTML element. Data attributes must be named data-{componentname}-{key}, e.g. data-o-share-id.
> - https://origami.ft.com/spec/v1/components/javascript/#data-attributes-on-owned-dom

**Comment by notlee** [comment]
nice  👍 https://github.com/Financial-Times/create-origami-component/pull/214
