### ISSUE TITLE
Avoid "we"/"let's" in tutorials?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-website#287]
[This tweet](https://twitter.com/notleemoody/status/1331189298675249153) got me thinking we shouldn't use "we"/"let's" in tutorials. Instead we should be more precise.

```diff
- So let's begin by creating a new directory to work in.
+ Begin by creating a new directory to work in.
```

```diff
- Let's head over to the striped variation of o-table in the registry, and copy that HTML in under our content.
+ Visit o-table in the registry, find the striped variation demo, and copy its HTML under your content.
```

```diff
- Let's break this down a little.
+ The following sections explain what [x] means in detail.
```

```diff
- Now let's add themes to our `o-example` component. 
+ Next add themes to your o-example component. 
+[or delete given the next section is large and has a heading]
```

```diff
- To see these Github Actions in practise let's release our component.
+ You will see these Github Actions in practise when you release your component in the next section.
```

We should aim to remain [conversational and prefer "we" over "I"](https://origami.ft.com/docs/principles/tone-and-language/#be-conversational) whilst avoiding "we"/"let's" in tutorials to be precise and direct. Thoughts? I bet there are professional content writers with good opinions but a quick web search didn't help me

**Comment by AniaMakes** [comment]
🤔  It feels like the `+` versions are less ambiguous and have more concrete steps. `visit o-table..` -  it has three steps, each separated by a comma making it easier to follow. `The following sections...` avoids "break this down" phrasing - it is very common in speech but due to the possible meaning of "breaking down" (damaging what we made) may confuse non-native speakers.

Maybe it's these particular examples, but I prefer the `+` version for each of them.

**Comment by notlee** [comment]
I think you're right that it might be these examples, I should have resisted updating other wording. What do you feel about these examples?

```diff
- Let's head over to the striped variation of o-table in the registry, and copy that HTML in under our content.
+ Visit the striped variation of o-table in the registry, and copy that HTML in under our content.
```

```diff
- Let's break this down a little.
+ The next section breaks this down a little.
```

**Comment by AniaMakes** [comment]
When you put it that way, I have no strong preferences either way. Might be worth asking around among non-native speakers, non-techy people, and neurodiverse folks - those are the groups that I can see having stronger opinions as to what they find easier to follow.

**Comment by notlee** [comment]
There's a lot of chat in the Slack thread. I'll aim to post a summary here later :)

**Comment by bjfletcher** [comment]
I like both, I like slightly more the "let's/we" ones, because they feel more friendly & approachable.

I'm a lot less fussy about English than most, I think, because it's my 2nd language and I'm more adaptable to different English usages/quirks/accents/styles.

By the way, this one looks a bit long...

```diff
- Let's head over to the striped variation of o-table in the registry, and copy that HTML in under our content.
+ Visit the striped variation of o-table in the registry, and copy that HTML in under our content.
```

could be...

```diff
+ o-table's [striped variation] can be below the content.
```

with the link pointing to the HTML for the table, perhaps? Good question & I hope you enjoy the discussion and find your ideal solution. Good luck!

**Comment by chee** [comment]
my feeling is that some people find the we/let's language warm, and others find it patronizing.
some people find the other language precise and clear and others find it cold and uninviting.

i would rather we were warm, and risk being patronizing than that we are cold and risk pushing people away.

@apaleslimghost mentioned that when reviewing docs with people the we/let's type language actually helps understanding.
 
> i’ll always fight for casual and friendly language in tutorials and documentation. i find it actually helps understanding. 
> if the text is too formal, in my experience people will skim the whole thing looking for what they want, when what they need is to go through it step by step

**Comment by chee** [comment]
just as a note, in the other branch of that Tweet the author said they were trolling. https://twitter.com/jaffathecake/status/1331208918199046147

**Comment by notlee** [comment]
>i would rather we were warm, and risk being patronizing than that we are cold and risk pushing people away.

Other feedback in the channel pointed to potential access problems of more verbose, less precise language. I think those concerns should come first. However it's going to be very hard to say what impact if any "we"/"let's" language has without quite a lot of work researching with our users. Not something I think is worthwhile for our 5 tutorials unless we expect a significant impact. If anyone can point to existing research that would be great but in the meantime I'm closing this issue
